[package]
name = "rcanary"
version = "0.1.0"
authors = ["Ng Guoyou <ng.guoyou@gmail.com>"]

[[bin]]
name = "rcanary"
test = true

[dependencies]
docopt = "0.7"
env_logger = "0.4"
hyper = "0.10"
lettre = "0.6"
log = "0.3"
rustc-serialize = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
toml = "0.4"
ws = "0.7"
