[package]
name = "rcanary"
version = "0.1.0"
authors = ["Ng Guoyou <ng.guoyou@gmail.com>"]

[[bin]]
name = "rcanary"
test = true

[dependencies]
docopt = "0.7"
env_logger = "0.3"
hyper = "0.9"
lettre = "0.6"
log = "0.3"
rustc-serialize = "0.3"
time = "0.1"
toml = "0.2"
ws = "0.5"
