version: "2.0"
services:
  rcanary:
    build: .
    restart: always
    environment:
      TZ: "Asia/Singapore"
    ports:
      - "8099:8099"
    volumes:
      - ./config:/app/config:ro
      - logs:/app/logs
volumes:
  logs: {}
